### ISSUE TITLE
rmvb crashing w/ amlplayer

### ISSUE THREAD

**Issue by yang299kms** [Pivosgroup/buildroot-linux#26]
with the beta3 git: 20121209-951088a, rmvb plays but no sound. when i try to stop the video xbmc crashes and restarts. my audio output is set for receiver capable for all the settings and 5.1, i also tried with 2.1 same result.

22:41:35 T:1261433952  NOTICE: CAMLPlayer::Process  
22:41:35 T:1261433952   DEBUG: CAMLPlayer::Process: URL=nfs://10.0.1.18/volume1/Misc/NGEW TVB/HAL-26-TVBN.rmvb  
22:41:35 T:1261433952   DEBUG: player init......  
22:41:35 T:1093865120   DEBUG: ------ Window Init (DialogBusy.xml) ------  
22:41:35 T:1093865120   DEBUG: Window DialogBusy.xml was already loaded  
22:41:35 T:1093865120   DEBUG: Alloc resources: 0.14m  
22:41:35 T:1194775648   DEBUG: CFileURLProtocol::Open filename2(nfs://10.0.1.18/volume1/Misc/NGEW TVB/HAL-26-TVBN.rmvb)  
22:41:35 T:1194775648   DEBUG: CNFSFile::Open - opened volume1/Misc/NGEW TVB/HAL-26-TVBN.rmvb  
22:41:36 T:1261433952   DEBUG: ScanForExternalSubtitles: Searching for subtitles...  
22:41:36 T:1261433952   DEBUG: ScanForExternalSubtitles: END (total time: 236 ms)  
22:41:37 T:1261433952   DEBUG: CAnnouncementManager - Announcement: OnSpeedChanged from xbmc  
22:41:37 T:1261433952   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnSpeedChanged  
22:41:37 T:1261433952   DEBUG: CAMLPlayer::SetVolume(1.000000)  
22:41:37 T:1261433952   DEBUG: CAMLPlayer::SetAVDelay (0.000000)  
22:41:37 T:1261433952   DEBUG: CAMLPlayer::GetActualFPS:m_video_fps(12.000000)  
22:41:37 T:1261433952   DEBUG: Process - change configuration. 720x408. framerate: 12.00. format: BYPASS  
22:41:37 T:1261433952  NOTICE: Display resolution DESKTOP : 1920x1080 @ 60.00 - Full Screen (16)  
22:41:37 T:1273767008  NOTICE: Thread CAMLSubTitleThread start, auto delete: false  
22:41:37 T:1273767008   DEBUG: CAMLSubTitleThread::Process begin  
22:41:37 T:1321731168    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy  
22:41:37 T:1093865120  NOTICE: Using GL_TEXTURE_2D  
22:41:37 T:1093865120   DEBUG: GL: Requested render method: 0  
22:41:37 T:1093865120  NOTICE: GL: Using BYPASS render method  
22:41:37 T:1093865120  NOTICE: GL: GL_ARB_texture_rectangle not supported and OpenGL version is not 2.x  
22:41:37 T:1093865120  NOTICE: GL: Reverting to POT textures  
22:41:37 T:1093865120   DEBUG: CLinuxRendererGLES: Reorder drawpoints due to method change from 1 to 272  
22:41:37 T:1093865120   DEBUG: Activating window ID: 12005  
22:41:37 T:1093865120   DEBUG: ------ Window Deinit (MyVideoNav.xml) ------  
22:41:37 T:1321731168    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy  
22:41:37 T:1093865120   DEBUG: ------ Window Init (VideoFullScreen.xml) ------  
22:41:37 T:1093865120    INFO: Loading skin file: VideoFullScreen.xml, load type: KEEP_IN_MEMORY  
22:41:38 T:1321731168    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy  
22:41:38 T:1093865120   DEBUG: Load VideoFullScreen.xml: 448.42ms  
22:41:38 T:1093865120   DEBUG: Alloc resources: 464.20ms  (462.06 ms skin load)  
22:41:38 T:1093865120   DEBUG: CGUIInfoManager::SetCurrentMovie(nfs://10.0.1.18/volume1/Misc/NGEW TVB/HAL-26-TVBN.rmvb)  
22:41:38 T:1321731168    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy  
22:41:38 T:1093865120   DEBUG: CAnnouncementManager - Announcement: OnPlay from xbmc  
22:41:38 T:1093865120   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnPlay  
22:41:38 T:1093865120   DEBUG: ------ Window Deinit (DialogBusy.xml) ------  
22:41:38 T:1321731168    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy  
22:41:52 T:1093865120    INFO: Previous line repeats 52 times.  
22:41:52 T:1093865120   DEBUG: Keyboard: scancode: a6, sym: 00b2, unicode: 0000, modifier: 0  
22:41:52 T:1093865120   DEBUG: OnKey: stop (f0bc) pressed, action is Stop  
22:41:52 T:1093865120   DEBUG: CAMLPlayer::CloseFile  
22:41:52 T:1093865120   DEBUG: CAMLPlayer: waiting for threads to exit  
22:41:52 T:1321731168    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy  
22:41:52 T:1273767008   DEBUG: CAMLSubTitleThread::Process end  
22:41:52 T:1273767008   DEBUG: Thread CAMLSubTitleThread 1273767008 terminating  
22:41:52 T:1194775648   DEBUG: CFileURLProtocol::Close  
22:41:52 T:1194775648   DEBUG: CNFSFile::Close closing file volume1/Misc/NGEW TVB/HAL-26-TVBN.rmvb  
22:41:52 T:1321731168    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy

**Comment by davilla** [comment]
22:41:38 T:1321731168 INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy

I don't think you are running the right version or you have forced GUI sounds on, turn them off. CAMLPlayer does not use CAESinkALSA, in fact it suspends it while running. The fact that you have CAESinkALSA indicates that CAESinkALSA is not suspended.

**Comment by yang299kms** [comment]
i don't have gui sounds turned on, i don't hear any sounds when i'm navigating the gui. although i can't find a setting anywhere to enable or disable gui sounds. i can try rebuilding but this was built after a make dist clean last night

**Comment by davilla** [comment]
check guisettings.xml in userdata

**Comment by davilla** [comment]
"my audio output is set for receiver capable for all the settings and 5.1", only AC3 and DTS should be enabled. The other settings will cause problems until I enable the hardware.

**Comment by yang299kms** [comment]
i have guisoundmode set to 0  in my guisettings.xml

i also copied the media to the sd card just in case, i also unset all the other receiver options leaving only ac3 and dts,  but stil same result. 

23:34:31 T:1093865120   DEBUG: OnPlayMedia /media/usb0/TC-22-TVBN.rmvb
23:34:31 T:1093865120   DEBUG: CAnnouncementManager - Announcement: OnClear from xbmc
23:34:31 T:1093865120   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnClear
23:34:31 T:1093865120   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
23:34:31 T:1093865120   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
23:34:32 T:1093865120   DEBUG: CPlayerCoreFactory::GetPlayers(/media/usb0/TC-22-TVBN.rmvb)
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: system rules
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: system rules
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtv
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: myth/mms
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: streams
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvd
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: ifo
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvdimage
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: nsv
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: radio
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rm/rmvb
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: rm/rmvb
23:34:32 T:1093865120   DEBUG: CPlayerSelectionRule::GetPlayers: adding player: AMLPlayer (4) for rule: rm/rmvb
23:34:32 T:1093865120   DEBUG: CPlayerCoreFactory::GetPlayers: matched 1 rules with players
23:34:32 T:1093865120   DEBUG: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (1)
23:34:32 T:1093865120   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=0
23:34:32 T:1093865120   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
23:34:32 T:1093865120   DEBUG: CPlayerCoreFactory::GetPlayers: adding player: DVDPlayer (1)
23:34:32 T:1093865120   DEBUG: CPlayerCoreFactory::GetPlayers: adding player: AMLPlayer (4)
23:34:32 T:1093865120   DEBUG: CPlayerCoreFactory::GetPlayers: added 2 players
23:34:32 T:1093865120   DEBUG: SECTION:LoadDLL(libamplayer.so)
23:34:32 T:1093865120   DEBUG: Loading: libamplayer.so
23:34:32 T:1093865120   DEBUG: CSoftAE::Suspend - Suspending AE processing
23:34:32 T:1093865120  NOTICE: CAMLPlayer: Opening: /media/usb0/TC-22-TVBN.rmvb
23:34:32 T:1093865120   DEBUG: CRenderManager::UpdateDisplayLatency - Latency set to 0 msec
23:34:32 T:1093865120   DEBUG: LinuxRendererGL: Cleaning up GL resources
23:34:32 T:1186296928  NOTICE: Thread CAMLPlayer start, auto delete: false
23:34:32 T:1186296928  NOTICE: CAMLPlayer::Process
23:34:32 T:1186296928   DEBUG: CAMLPlayer::Process: URL=/media/usb0/TC-22-TVBN.rmvb
23:34:32 T:1186296928   DEBUG: player init......
23:34:32 T:1093865120   DEBUG: ------ Window Init (DialogBusy.xml) ------
23:34:32 T:1093865120   DEBUG: Window DialogBusy.xml was already loaded
23:34:32 T:1093865120   DEBUG: Alloc resources: 0.03m
23:34:33 T:1186296928   DEBUG: ScanForExternalSubtitles: Searching for subtitles...
23:34:33 T:1186296928   DEBUG: ScanArchiveForSubtitles:: Found file zip://%2fmedia%2fusb0%2fpvr.mythtv.cmyth-linux-arm.zip/pvr.mythtv.cmyth/
23:34:33 T:1186296928   DEBUG: ScanForExternalSubtitles: END (total time: 31 ms)
23:34:33 T:1203164256    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy
23:34:33 T:1186296928   DEBUG: CAnnouncementManager - Announcement: OnSpeedChanged from xbmc
23:34:33 T:1186296928   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnSpeedChanged
23:34:33 T:1186296928   DEBUG: CAMLPlayer::SetVolume(1.000000)
23:34:33 T:1186296928   DEBUG: CAMLPlayer::SetAVDelay (0.000000)
23:34:33 T:1186296928   DEBUG: CAMLPlayer::GetActualFPS:m_video_fps(12.000000)
23:34:33 T:1186296928   DEBUG: Process - change configuration. 720x408. framerate: 12.00. format: BYPASS
23:34:33 T:1186296928  NOTICE: Display resolution DESKTOP : 1920x1080 @ 60.00 - Full Screen (16)
23:34:33 T:1369232480  NOTICE: Thread CAMLSubTitleThread start, auto delete: false
23:34:33 T:1369232480   DEBUG: CAMLSubTitleThread::Process begin
23:34:34 T:1203164256    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy
23:34:34 T:1093865120    INFO: Previous line repeats 1 times.
23:34:34 T:1093865120  NOTICE: Using GL_TEXTURE_2D
23:34:34 T:1093865120   DEBUG: GL: Requested render method: 0
23:34:34 T:1093865120  NOTICE: GL: Using BYPASS render method
23:34:34 T:1093865120  NOTICE: GL: GL_ARB_texture_rectangle not supported and OpenGL version is not 2.x
23:34:34 T:1093865120  NOTICE: GL: Reverting to POT textures
23:34:34 T:1093865120   DEBUG: CLinuxRendererGLES: Reorder drawpoints due to method change from 1 to 272
23:34:34 T:1093865120   DEBUG: Activating window ID: 12005
23:34:34 T:1093865120   DEBUG: ------ Window Deinit (MyVideoNav.xml) ------
23:34:34 T:1093865120   DEBUG: ------ Window Init (VideoFullScreen.xml) ------
23:34:34 T:1093865120    INFO: Loading skin file: VideoFullScreen.xml, load type: KEEP_IN_MEMORY
23:34:34 T:1203164256    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy
23:34:34 T:1093865120   DEBUG: Load VideoFullScreen.xml: 263.97ms
23:34:34 T:1093865120   DEBUG: Alloc resources: 335.41ms  (333.34 ms skin load)
23:34:35 T:1102410848   ERROR: CAESinkALSA::HandleError(snd_pcm_wait) - underrun
23:34:35 T:1203164256    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy
23:34:35 T:1102410848    INFO: CAESinkALSA - ALSA: pcm_hw.c:138:(sync_ptr1) SNDRV_PCM_IOCTL_SYNC_PTR failed (-32): Broken pipe
23:34:35 T:1102410848   ERROR: CAESinkALSA::HandleError(snd_pcm_avail) - underrun
23:34:35 T:1102410848    INFO: CAESinkALSA - ALSA: pcm_hw.c:138:(sync_ptr1) SNDRV_PCM_IOCTL_SYNC_PTR failed (-32): Broken pipe
23:34:35 T:1102410848   ERROR: CAESinkALSA::HandleError(snd_pcm_avail) - underrun
23:34:35 T:1093865120   DEBUG: CGUIInfoManager::SetCurrentMovie(/media/usb0/TC-22-TVBN.rmvb)
23:34:35 T:1093865120   DEBUG: CAnnouncementManager - Announcement: OnPlay from xbmc
23:34:35 T:1093865120   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnPlay
23:34:35 T:1093865120   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
23:34:35 T:1203164256    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy
23:34:41 T:1093865120    INFO: Previous line repeats 19 times.
23:34:41 T:1093865120   DEBUG: Keyboard: scancode: 1c, sym: 000d, unicode: 0000, modifier: 0
23:34:41 T:1093865120   DEBUG: OnKey: return (f00d) pressed, action is OSD
23:34:41 T:1093865120   DEBUG: ------ Window Init (VideoOSD.xml) ------
23:34:41 T:1093865120    INFO: Loading skin file: VideoOSD.xml, load type: KEEP_IN_MEMORY
23:34:41 T:1203164256    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy
23:34:41 T:1093865120   DEBUG: Load VideoOSD.xml: 407.25ms
23:34:41 T:1093865120   DEBUG: Alloc resources: 489.75ms  (420.77 ms skin load)
23:34:41 T:1203164256    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy
23:34:42 T:1093865120    INFO: Previous line repeats 4 times.
23:34:42 T:1093865120   DEBUG: Keyboard: scancode: 6a, sym: 0113, unicode: 0000, modifier: 0
23:34:42 T:1093865120   DEBUG: OnKey: right (f083) pressed, action is Right
23:34:43 T:1203164256    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy
23:34:43 T:1093865120    INFO: Previous line repeats 1 times.
23:34:43 T:1093865120   DEBUG: Keyboard: scancode: 1c, sym: 000d, unicode: 0000, modifier: 0
23:34:43 T:1093865120   DEBUG: OnKey: return (f00d) pressed, action is Select
23:34:43 T:1093865120   DEBUG: ExecuteXBMCAction : Translating PlayerControl(Stop)
23:34:43 T:1093865120   DEBUG: ExecuteXBMCAction : To PlayerControl(Stop)
23:34:43 T:1093865120   DEBUG: CAMLPlayer::CloseFile
23:34:43 T:1093865120   DEBUG: CAMLPlayer: waiting for threads to exit
23:34:43 T:1203164256    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy
23:34:43 T:1369232480   DEBUG: CAMLSubTitleThread::Process end
23:34:43 T:1369232480   DEBUG: Thread CAMLSubTitleThread 1369232480 terminating
23:34:43 T:1203164256    INFO: CAESinkALSA - ALSA: pcm_hw.c:1293:(snd_pcm_hw_open) open '/dev/snd/pcmC0D0p' failed (-16): Device or resource busy

**Comment by yang299kms** [comment]
i undid this change and the audio problems w/ rmvb is fixed

https://github.com/Pivosgroup/xbmc/commit/ff91e9204912b416a98d1a6f849776cec28ef451

**Comment by davilla** [comment]
humm, strange. the long pause error will return under linux

**Comment by yang299kms** [comment]
yeah, i can live w/ pause not working, wife needs rmvb unfortunately.

**Comment by thewhitestig** [comment]
I had the same problem with 121512 build, but got better with latest private build.  It doesn't crash anymore and the sound is back, however it sounds distorted.

**Comment by davilla** [comment]
"sounds distorted", in what way ?

**Comment by thewhitestig** [comment]
It sounds clipped just like when someone maxed out the volume.  Also system volume has no affect on rmvb sound level.

**Comment by davilla** [comment]
lost volume control for amlplayer is fixed now, this should fix the audio distortion by allowing you to reduce the volume.

**Comment by thewhitestig** [comment]
With latest official build, I can now control the sound level by system volume, but it is still distorted even at very low level.
Attached a sample rmvb file in case you want to reproduce it on your own setup.
https://www.dropbox.com/s/itlcwel86altew7/InitialD%20-S4E01-Project%20D.rmvb

Also, the problem where sound level jump back to max after a seek-fwd/bkwd still happens on rmvb file.  All other formats are okay.

**Comment by davilla** [comment]
volume restored on seeks.
not sure about this sample, it sounds fine to me, crappy encode ? I did notice it's using the 'cook' audio.

**Comment by yang299kms** [comment]
also sounds ok to me, compared with vlc on my laptop and thru my denon av

**Comment by thewhitestig** [comment]
I think it's related to HDMI handshaking (which might be totally unrelated to this original ticket).  I've upgraded my other setup this evening, and it sounds okay.  It seems like it's only happening on my Panasonic LCD, and I could get it to sound normally by either wait until XIOS fully boot up before turning on TV, or switching input back and forth which might have triggered another handshake.

**Comment by davilla** [comment]
Also 720p vs 1080p DISPLAY setting can effect audio. Got to love HDMI :(

My Westinghouse audio will crap out every now and then, normally right before it refused any IR control and I have to hard power cycle it.

**Comment by davilla** [comment]
still a problem ?

**Comment by yang299kms** [comment]
latest build has no sound, but not sure if its because i reverted the kernel changes for sizes. i'll test w/ different image tomorrow night.

**Comment by thewhitestig** [comment]
I had the same problem with Speedster's nightly load as well.

**Comment by davilla** [comment]
only with amlplayer or only amlplayer playing realmedia ?

**Comment by yang299kms** [comment]
amlplayer w/ any kind of media gets no sound. seems also some o the video controls don't work either, if i try to skip chapters it keeps playing and i lose control of the box. had to ssh in and reboot

**Comment by davilla** [comment]
maybe a broked build ?

**Comment by davilla** [comment]
There's something wrong with amlplayer/libamplayer, even normal mkv;s will borke it. Not sure when or what caused it. I doubt it's the kernel pcm buffer size change as I can revert that and get the same thing.

**Comment by davilla** [comment]
Note, this only effects M1's. M3's are fine. That suggests kernel or libamplayer.

**Comment by yang299kms** [comment]
dont' have issues using Git:20130106-5d66f5d

**Comment by davilla** [comment]
can you show that commit ?

**Comment by yang299kms** [comment]
the version i'm running was right after you fixed the 720p playback of mpeg2ts. might have merged w/ rc3 myself. forgot if i did it w/ this build or an earlier one.

**Comment by davilla** [comment]
commit 6c15830cdaf3abed8678ec14cf9c1ab94d5b0fe2
Author: davilla davilla@4pi.com
Date:   Tue Jan 1 12:32:54 2013 -0500

```
[aml] fixed, playback of 60 fps video content
```

**Comment by yang299kms** [comment]
so after many hours of trying out all the buildroot commits  since my good version i found the checkin that broke aml player:

commit 67129392c3f744f30f5cf6781baa158ce0624f37
Author: davilla davilla@4pi.com
Date:   Fri Jan 11 13:34:42 2013 -0500

```
[aml] bump xbmc version to pickup audio fixes
```

before this checkin everything works fine, built using this checking and aml player is broken

**Comment by davilla** [comment]
fixed in https://github.com/Pivosgroup/buildroot-linux/commit/d55ab091e3dbfc147d4a180054b4a6cd707f2339

**Comment by yang299kms** [comment]
confirmed fixed
